# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-31 13:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DbClient',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('client_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='DbCommand',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cmd', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='DbLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=30)),
                ('client_name', models.CharField(max_length=30)),
                ('server_name', models.CharField(max_length=30)),
                ('server_ip', models.CharField(max_length=15)),
                ('cmd', models.CharField(max_length=60)),
                ('cmd_output', models.TextField()),
                ('run_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='DbServer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('server_name', models.CharField(max_length=30)),
                ('server_ip', models.CharField(max_length=15)),
                ('id_client_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.DbClient')),
            ],
        ),
        migrations.CreateModel(
            name='DbSystem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('os_platform', models.CharField(max_length=16)),
            ],
        ),
        migrations.AddField(
            model_name='dbserver',
            name='id_os_platform',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.DbSystem'),
        ),
        migrations.AddField(
            model_name='dbcommand',
            name='id_os_platform',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.DbSystem'),
        ),
    ]
