# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-14 13:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DbLdap',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_email', models.CharField(max_length=40)),
                ('userdn', models.CharField(max_length=40)),
                ('is_admin', models.BooleanField(default=False)),
            ],
        ),
    ]
