# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-16 12:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_dbldap'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dbldap',
            name='userdn',
            field=models.CharField(max_length=80),
        ),
    ]
