# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-16 13:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_auto_20161216_1204'),
    ]

    operations = [
        migrations.AddField(
            model_name='dbldap',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
