# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-16 13:26
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_dbldap_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='dbldap',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
