# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-16 13:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_dbldap_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dbldap',
            old_name='date',
            new_name='last_login',
        ),
    ]
