# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-16 13:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_auto_20161216_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dbldap',
            name='last_login',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
