# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-16 13:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_remove_dbldap_last_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='dbldap',
            name='last_login',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
