# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-16 14:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0009_dbldap_last_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='dbldap',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
