# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-20 10:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0011_dbldap_is_authenticated'),
    ]

    operations = [
        migrations.AddField(
            model_name='dbldap',
            name='is_anonymous',
            field=models.BooleanField(default=False),
        ),
    ]
