# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-20 11:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0013_auto_20161220_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dbldap',
            name='is_authenticated',
            field=models.BooleanField(default=False),
        ),
    ]
