# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-20 13:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0014_auto_20161220_1111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dbldap',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='dbldap',
            name='is_anonymous',
        ),
        migrations.RemoveField(
            model_name='dbldap',
            name='is_authenticated',
        ),
        migrations.RemoveField(
            model_name='dbldap',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='dbldap',
            name='last_login',
        ),
    ]
